### ISSUE TITLE
[ Urgent ] Not teleporting players, and not allowing players to have more homes

### ISSUE THREAD

**Issue by Yomamaeatstoes** [Loving11ish/EpicHomes-ALPHA-BETA-Builds#1]
![Screenshot 4_21_2023 8_29_52 PM](https://user-images.githubusercontent.com/114538961/233752092-9a2660cc-6ab8-4336-a074-374e252bc4fc.png)
![Screenshot 4_21_2023 8_29_55 PM](https://user-images.githubusercontent.com/114538961/233752094-43cfc52b-a2b2-488c-912d-014e9859f2e6.png)

Yes I have 8 homes, and but this user can only set 7.

So it looks like an issue deleting homes and stuff.

AN issue of not being able to teleport to set homes https://youtu.be/Ljy1qFSlH-s
Config

https://mclo.gs/0ibvIpG

Messages.yml 

https://mclo.gs/t19sxdL

Usermap.yml

https://mclo.gs/Qn8Fbzz

No error messages

**Comment by Loving11ish** [comment]
Now fixed in v1.0.0-BETA-02.
