### ISSUE TITLE
Spamming chat message 

### ISSUE THREAD

**Issue by Yomamaeatstoes** [Loving11ish/EpicHomes-ALPHA-BETA-Builds#2]
Whenever I type a command, it creates a message in the console. "nucklear issued server command: /spawn" and it says " [/home, /sethome, /delhome, /h, /eh, /delhome, /homes, /epichomes] " It does this for every console message"

**Comment by Loving11ish** [comment]
This is an oversight left over debugging message.  It has been removed!
